/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AttendanceUpdateManyWithoutEmployeesInput } from "./AttendanceUpdateManyWithoutEmployeesInput";
import { ValidateNested, IsOptional, IsDate, IsString } from "class-validator";
import { Type } from "class-transformer";
import { LeaveUpdateManyWithoutEmployeesInput } from "./LeaveUpdateManyWithoutEmployeesInput";
import { PayrollUpdateManyWithoutEmployeesInput } from "./PayrollUpdateManyWithoutEmployeesInput";

@InputType()
class EmployeeUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AttendanceUpdateManyWithoutEmployeesInput,
  })
  @ValidateNested()
  @Type(() => AttendanceUpdateManyWithoutEmployeesInput)
  @IsOptional()
  @Field(() => AttendanceUpdateManyWithoutEmployeesInput, {
    nullable: true,
  })
  attendances?: AttendanceUpdateManyWithoutEmployeesInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  dateOfBirth?: Date | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  dateOfJoining?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  designation?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: () => LeaveUpdateManyWithoutEmployeesInput,
  })
  @ValidateNested()
  @Type(() => LeaveUpdateManyWithoutEmployeesInput)
  @IsOptional()
  @Field(() => LeaveUpdateManyWithoutEmployeesInput, {
    nullable: true,
  })
  leaves?: LeaveUpdateManyWithoutEmployeesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => PayrollUpdateManyWithoutEmployeesInput,
  })
  @ValidateNested()
  @Type(() => PayrollUpdateManyWithoutEmployeesInput)
  @IsOptional()
  @Field(() => PayrollUpdateManyWithoutEmployeesInput, {
    nullable: true,
  })
  payrolls?: PayrollUpdateManyWithoutEmployeesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phone?: string | null;
}

export { EmployeeUpdateInput as EmployeeUpdateInput };
